# Generated by Django 5.2.5 on 2025-09-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
